# Google Sheets credentials
[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"

# Chef password
chef_password = "your-secure-password"
token = "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"
owner = "aidarpavl"
repo = "Stolovaia27"
branch = "main"
menu_path = "menu.csv"
